# Generated by Django 4.2.2 on 2023-06-28 17:32

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='цена')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='скидка')),
                ('preview', models.ImageField(blank=True, upload_to=shop.models.car_preview_directory_path, verbose_name='превью')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('car_class', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e'), ('F', 'f'), ('S', 's'), ('M', 'm'), ('J', 'j')], max_length=1, verbose_name='класс автомобиля')),
                ('doors_qty', models.PositiveSmallIntegerField(verbose_name='количество дверей')),
                ('seats_qty', models.PositiveSmallIntegerField(verbose_name='количеств мест')),
                ('transmission', models.CharField(choices=[('механика', 'Механика'), ('автомат', 'Автомат'), ('робот', 'Робот'), ('вариатор', 'Вариатор')], max_length=8, verbose_name='коробка')),
                ('engine_power', models.PositiveSmallIntegerField(verbose_name='мощность двигателя (л.с.)')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='объём двигателя (л)')),
                ('drive', models.CharField(choices=[('задний', 'Задний'), ('передний', 'Передний'), ('полный', 'Полный')], max_length=8, verbose_name='привод')),
                ('consumption', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='расход')),
                ('trunk_volume', models.PositiveSmallIntegerField(verbose_name='объём багажника (л)')),
                ('fuel_tank_capacity', models.PositiveSmallIntegerField(verbose_name='объём топливного бака (л)')),
                ('max_speed', models.PositiveSmallIntegerField(verbose_name='максимальная скорость (км/ч)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shop.brand', verbose_name='бренд')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
            },
        ),
    ]
