# Generated by Django 4.2.2 on 2023-07-03 14:04

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_carimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title'], 'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.brand_image_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='изображение'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['title'], name='shop_brand_title_967c27_idx'),
        ),
    ]
