# Generated by Django 4.2.2 on 2023-07-03 14:17

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_brand_options_alter_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', 'model', '-price'], 'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('S', 'S'), ('M', 'M'), ('J', 'J')], max_length=1, verbose_name='класс автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='preview',
            field=models.ImageField(blank=True, upload_to=shop.models.car_preview_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='превью'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model', '-price'], name='shop_car_brand_i_434fd5_idx'),
        ),
    ]
